export const analyzedBlockTypes = [
	'1-column-heading',
	'1-column-wysiwyg',
	'1-column-image',
	'1-column-wide-image',
	'1-column-wysiwyg-with-left-floating-image',
	'1-column-wysiwyg-with-right-floating-image',
	'1-column-video',
	'1-column-audio',
	'1-column-map',
	'1-column-iframe',
	'1-column-carousel',
	'1-column-code',
	'1-column-other',
	'2-column-wysiwyg',
	'2-column-image',
	'2-column-video',
	'2-column-audio',
	'2-column-map',
	'2-column-iframe',
	'2-column-carousel',
	'2-column-code',
	'2-column-other',
	'3-column-wysiwyg',
	'3-column-image',
	'3-column-video',
	'3-column-audio',
	'3-column-map',
	'3-column-iframe',
	'3-column-carousel',
	'3-column-code',
	'3-column-other',
	'4-column-wysiwyg',
	'4-column-image',
	'4-column-video',
	'4-column-audio',
	'4-column-map',
	'4-column-iframe',
	'4-column-carousel',
	'4-column-code',
	'4-column-other',
	'5-column-wysiwyg',
	'5-column-image',
	'5-column-video',
	'5-column-audio',
	'5-column-map',
	'5-column-iframe',
	'5-column-carousel',
	'5-column-code',
	'5-column-other',
] as const satisfies `${1 | 2 | 3 | 4 | 5}-column-${(typeof blockContentTypes)[number]}`[];

export const blockContentTypes = [
	'heading',
	'wysiwyg',
	'image',
	'wide-image',
	'wysiwyg-with-left-floating-image',
	'wysiwyg-with-right-floating-image',
	'video',
	'audio',
	'map',
	'iframe',
	'carousel',
	'code',
	'tab-ui',
	'accordion-ui',
	'other',
] as const;

export const description = [
	`Block type: ${analyzedBlockTypes.join(', ')}`,
	'',
	'Format: `${column}-column-${type}`',
	'Available columns: 1, 2, 3, 4, 5',
	'Available types: ' + blockContentTypes.join(', '),
	'- heading: Heading text.',
	'- wysiwyg: Group of elements with paragraph etc.',
	'- image: Image.',
	'- wide-image: Wide image.',
	'- wysiwyg-with-left-floating-image: WYSIWYG with left floating image.',
	'- wysiwyg-with-right-floating-image: WYSIWYG with right floating image.',
	'- video: Video.',
	'- audio: Audio.',
	'- map: Map. Ex: Google Maps.',
	'- iframe: Iframe. Ex: YouTube.',
	'- carousel: Carousel UI.',
	'- code: Programming or markup code.',
	'- tab-ui: Tab UI.',
	'- accordion-ui: Accordion UI.',
	'- other: Other.',
].join('\n');
