import type { analyzedBlockTypes } from '../analyzed-block-types.js';
import type { blocks } from '@burger-editor/legacy/v3';

export const blockTypeMappings = {
	'1-column-heading': 'title',
	'1-column-wysiwyg': 'wysiwyg',
	'1-column-image': 'image1',
	'1-column-wide-image': 'image1',
	'1-column-wysiwyg-with-left-floating-image': 'textFloatImage1',
	'1-column-wysiwyg-with-right-floating-image': 'textFloatImage2',
	'1-column-video': 'wysiwyg',
	'1-column-audio': 'wysiwyg',
	'1-column-map': 'googleMaps',
	'1-column-iframe': 'wysiwyg',
	'1-column-carousel': 'gallery',
	'1-column-code': 'wysiwyg',
	'1-column-other': 'wysiwyg',
	'2-column-wysiwyg': 'wysiwyg2',
	'2-column-image': 'image2',
	'2-column-video': 'wysiwyg2',
	'2-column-audio': 'wysiwyg2',
	'2-column-map': 'wysiwyg2',
	'2-column-iframe': 'wysiwyg2',
	'2-column-carousel': 'wysiwyg2',
	'2-column-code': 'wysiwyg2',
	'2-column-other': 'wysiwyg2',
	'3-column-wysiwyg': 'wysiwyg',
	'3-column-image': 'image3',
	'3-column-video': 'wysiwyg',
	'3-column-audio': 'wysiwyg',
	'3-column-map': 'wysiwyg',
	'3-column-iframe': 'wysiwyg',
	'3-column-carousel': 'wysiwyg',
	'3-column-code': 'wysiwyg',
	'3-column-other': 'wysiwyg',
	'4-column-wysiwyg': 'wysiwyg',
	'4-column-image': 'image4',
	'4-column-video': 'wysiwyg',
	'4-column-audio': 'wysiwyg',
	'4-column-map': 'wysiwyg',
	'4-column-iframe': 'wysiwyg',
	'4-column-carousel': 'wysiwyg',
	'4-column-code': 'wysiwyg',
	'4-column-other': 'wysiwyg',
	'5-column-wysiwyg': 'wysiwyg',
	'5-column-image': 'image5',
	'5-column-video': 'wysiwyg',
	'5-column-audio': 'wysiwyg',
	'5-column-map': 'wysiwyg',
	'5-column-iframe': 'wysiwyg',
	'5-column-carousel': 'wysiwyg',
	'5-column-code': 'wysiwyg',
	'5-column-other': 'wysiwyg',
} as const satisfies Record<(typeof analyzedBlockTypes)[number], keyof typeof blocks>;
