name: Test

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 22

      - name: Cache dependencies
        id: cache-depends
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: '**/node_modules'
          key: cache-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-depends.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --check-files

      - name: Build
        run: yarn build

      - name: List
        run: yarn list

      - name: Test
        run: yarn test
